Add Optimization theory section
AeroPython/awesome-scientific-computing pull request #4
Opened 2023-11-28 00:59 UTC by tapyu

2023-11-28 08:50 UTC, astrojuanlu requested changes
Thanks for your PR @tapyu! Could you keep only the free and open resources?

2023-11-28 17:15 UTC, tapyu commented on README.md
> +- [EE364A - Convex Optimization I](https://see.stanford.edu/Course/EE364A) and [Material](https://web.stanford.edu/class/ee364a/) - Stanford Engineering Everywhere - Convex Optimization I course.
Hi! the Stanford course platform "Stanford Engineering Everywhere" is free (in the "free beer" sense") and open. There is not charge to access this course, at all.

2023-11-28 18:24 UTC, tapyu commented
I am not sure if it is necessary, but I just added the free icon to make it clear that there is no charge in the "Stanford Engineering Everywhere" platform.

2023-11-28 22:15 UTC, astrojuanlu commented
Oh, thanks! Please solve the merge conflicts and I'll merge

2023-11-29 01:54 UTC, tapyu commented
Done.

2023-11-30 10:35 UTC, closed without merging